name: "Deploy to NuGet"

on:
  push:
    tags:
      - "v*"

env:
  SOLUTION_PATH: "OpenMetrc.sln"
  PROJECT_PATH: "src/OpenMetrc/OpenMetrc.csproj"
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_SOURCE_URL: "https://api.nuget.org/v3/index.json"

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install dotnet"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: "Restore packages"
        run: dotnet restore

      - name: "Build projects"
        run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore --configuration Release

      - name: "Test project"
        run: dotnet test ${{ env.SOLUTION_PATH }} --no-build --verbosity normal --configuration Release
        env:
          METRC_API_KEYS: ${{secrets.METRC_API_KEYS}}

      - name: "Get Version"
        id: version
        uses: battila7/get-version-action@v2

      - name: "Pack project"
        run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: "Push package"
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg -k ${{ secrets.NUGET_API_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}
